
const dummyData = [
    "Australia",
    "Austria",
    "Belgium",
    "Canada",
    "Colombia",
    "Czech Republic",
    "Denmark",
    "Ecuador",
    "Finland",
    "France",
    "Germany",
    "Global",
    "Greece",
    "Guatemala",
    "Hong Kong",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Italy",
    "Japan",
    "Lithuania",
    "Malaysia",
    "Mexico",
    "Netherlands",
    "New Zealand",
    "Norway",
    "Philippines",
    "Poland",
    "Portugal",
    "Singapore",
    "Slovakia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Taiwan",
    "Turkey",
    "United Kingdom",
    "United States",
    "Iceland",
    "Argentina",
    "Chile",
    "Costa Rica",
    "Dominican Republic",
    "Honduras",
    "Panama",
    "Paraguay",
    "Peru",
    "Estonia",
    "Latvia",
    "Uruguay",
    "Luxembourg",
    "Bolivia",
    "Nicaragua",
    "El Salvador",
    "Egypt",
    "Thailand",
    "Vietnam",
    "Israel",
    "Romania",
    "South Africa",
    "Bulgaria",
    "United Arab Emirates",
    "Saudi Arabia",
    "India",
    "Russia",
    "Ukraine",
    "Andorra",
    "Morocco",
    "South Korea"
    ]
